---
title: "geofacet"
author: "Fabian Koch"
date: "12 3 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(geofacet)
```

```{r}
GebKeySB <- tribble(
      ~"NAME", ~"KEY",
      "Innenstadt-West", "030",
      "Innenstadt-Nord", "040",
      "Innenstadt-Ost", "070",
      "Eving", "001",
      "Scharnhorst", "002",
      "Brackel", "003",
      "Aplerbeck", "004",
      "Hörde", "005",
      "Hombruch", "006",
      "Lütgendortmund", "007",
      "Huckarde", "008",
      "Mengede", "009")

#Extraktion Factor Level aus DF
fctlevel_SB <- GebKeySB %>% pull(NAME)


#download and extract zipped shapefile from DO HP
temp <- tempfile()
download.file("https://geoweb1.digistadtdo.de/doris_gdi/opengeodata/statistik/Stadtbezirk.zip",temp)
unzip(temp, exdir = "./shapes/SB_DO")


SB_DO <- sf::st_read(dsn = "./shapes/SB_DO/Stadtbezirk.shp") %>% 
  # Anpassen des shapefiles
  mutate(
    NAME = as.factor(NAME),
    NAME = forcats::fct_recode(NAME,
                               "Scharnhorst" = "Schanhorst",
                               "Lütgendortmund" = "Luetgendortmund",
                               "Hörde" = "Hoerde",
                               "Innenstadt-West" = "Innenstadt West",
                               "Innenstadt-Ost" = "Innenstadt Ost",
                               "Innenstadt-Nord" = "Innenstadt Nord"),
    NAME = factor(NAME, levels = fctlevel_SB)) %>% 
  left_join(GebKeySB, by = "NAME") %>% 
  select(-FACH_ID)






Altersgruppen <- readxl::read_excel("./data/Altersgruppen.xlsx") %>% 
  rename(Gebiet = "Stadtbezirk") %>% 
  mutate(Wert = round(Wert/1000),0)

Dortmund <- Altersgruppen %>% 
  group_by(Jahr, Altersgruppe) %>% 
  summarise(Wert = sum(Wert)) %>% 
  mutate(
    Gebiet = "Dortmund",
    Key = NA) %>% 
  mutate(Wert = round(Wert/1000),0)
  
Altergruppen_DO <- Altersgruppen %>% 
  bind_rows(Dortmund) 
```




```{r}
# https://hafen.github.io/grid-designer/
SB_DO <- data.frame(
  row = c(1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4),
  col = c(2, 3, 4, 2, 3, 4, 1, 2, 3, 4, 2, 3),
  code = c("Mengede", "Eving", "Scharnhorst", "Huckarde", "Innenstadt-Nord", "Brackel", "Lütgendortmund", "Innenstadt-West", "Innenstadt-Ost", "Aplerbeck", "Hombruch", "Hörde"),
  name = c("Mengede", "Eving", "Scharnhorst", "Huckarde", "Innenstadt-Nord", "Brackel", "Lütgendortmund", "Innenstadt-West", "Innenstadt-Ost", "Aplerbeck", "Hombruch", "Hörde"),
  stringsAsFactors = FALSE
)

```


```{r}

test <- plotly::ggplotly(ggplot(Altersgruppen) +
  geom_line(aes(x = Jahr, y = Wert, color = Altersgruppe)) +
  geofacet::facet_geo(facets = ~Gebiet, grid = SB_DO) +
  theme_minimal() + 
  labs(
      title = "Entwicklung der Hauptwohnbevölkerung in Stadtbezirken Dortmunds",
      subtitle = "nach Altersgruppen, 2010 bis 2021",
      caption = "",
      tag = "",
      fill = "") +
    xlab("") +
    ylab("Anzahl in Tausend") +
  theme(legend.position = "top"))

htmlwidgets::saveWidget(test, "./geofacet.html")
```

